### ISSUE TITLE
qalag.exe stopped working

### ISSUE THREAD

**Issue by reloxx13** [tverona1/QuestAppLauncher_Assets#4]
As of today your qalag exe stopped working.    
I guess oculus changed something on the endpoint u r using.   
And its not fixable cause there is no sourcecode.    

```
Traceback (most recent call last):
  File "QuestAssetGenerator.py", line 608, in launch_executable
    output = subprocess.check_output([bin_path] + args, stderr=subprocess.STDOUT)
  File "C:\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['QuestAppLauncher_Assets\\bin\\qalag.exe']' returned non-zero exit status 4294967295.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "QuestAssetGenerator.py", line 640, in <module>
    main()
  File "QuestAssetGenerator.py", line 109, in main
    download_latest_assets()
  File "QuestAssetGenerator.py", line 411, in download_latest_assets
    launch_executable([], galag_exe_full_path)
  File "QuestAssetGenerator.py", line 612, in launch_executable
    raise Exception(str.format(str(e) + ". Output: '%s'" % (e.output.decode(sys.stdout.encoding).rstrip()))) from e
Exception: Command '['QuestAppLauncher_Assets\\bin\\qalag.exe']' returned non-zero exit status 4294967295.. Output: '[22256] Failed to execute script QALAG
Traceback (most recent call last):
  File "QALAG.py", line 191, in <module>
  File "QALAG.py", line 33, in main
  File "QALAG.py", line 135, in download_images
  File "QALAG.py", line 113, in retrieve_package_name
  File "site-packages\requests\models.py", line 897, in json
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Retrieving Appinfo
```

**Comment by reloxx13** [comment]
it worked again, maybe it was just oculus having a problem. close for now

**Comment by reloxx13** [comment]
```
Traceback (most recent call last):
  File "QuestAssetGenerator.py", line 843, in launch_executable
    output = subprocess.check_output([bin_path] + args, stderr=subprocess.STDOUT)
  File "C:\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\xampp\\htdocs\\python\\QuestAppLauncher_Assets\\bin\\qalag.exe']' returned non-zero exit status 4294967295.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "QuestAssetGenerator.py", line 876, in <module>
    main()
  File "QuestAssetGenerator.py", line 146, in main
    download_latest_assets()
  File "QuestAssetGenerator.py", line 641, in download_latest_assets
    launch_executable([], qalag_exe_full_path)
  File "QuestAssetGenerator.py", line 847, in launch_executable
    raise Exception(str.format(str(e) + ". Output: '%s'" % (e.output.decode(sys.stdout.encoding).rstrip()))) from e
Exception: Command '['D:\\xampp\\htdocs\\python\\QuestAppLauncher_Assets\\bin\\qalag.exe']' returned non-zero exit status 4294967295.. Output: '[26028] Failed to execute script QALAG
Traceback (most recent call last):
  File "QALAG.py", line 191, in <module>
  File "QALAG.py", line 33, in main
  File "QALAG.py", line 135, in download_images
  File "QALAG.py", line 114, in retrieve_package_name
KeyError: 'data'
Retrieving Appinfo
.
Expected: 285
Retrieved: 285
Downloading images
Fetching package_name for app_id 2886115781495034'
```

Oculus changed sth an we got no sourcecode to fix it.

**Comment by tverona1** [comment]
Hey @reloxx13 sorry I haven't had a chance to look at this for some time :). Let me look at it this coming weekend. I think I have the source for qalag somewhere.

**Comment by reloxx13** [comment]
...
